source 'https://github.com/CocoaPods/Specs.git'

target 'AsyncExample iOS' do
    platform :ios, '8.0'
    use_frameworks!
    pod 'Async', :path => '../'
end
target 'AsyncExample iOSTests' do
    platform :ios, '8.0'
    use_frameworks!
    pod 'Async', :path => '../'
end
target 'AsyncExample OS X' do
    platform :osx, '10.10'
    use_frameworks!
    pod 'Async', :path => '../'
end
target 'AsyncExample OS XTests' do
    platform :osx, '10.10'
    use_frameworks!
    pod 'Async', :path => '../'
end



