source 'https://github.com/CocoaPods/Specs.git'

target 'AsyncExample iOS' do
    platform :ios, '8.0'
    use_frameworks!
    pod 'AsyncSwift', :path => '../'
end
target 'AsyncExample tvOS' do
    platform :tvos, '9.0'
    use_frameworks!
    pod 'AsyncSwift', :path => '../'
end
target 'AsyncExample OS X' do
    platform :osx, '10.10'
    use_frameworks!
    pod 'AsyncSwift', :path => '../'
end



